import Product from "./product";
import Supplier from "./supplier";

export interface CLIFormType {
  id: string;
  product: Product;
  batch: string;
  energy: string;
  renewenergy: string;
  water: string;
  waterrec: string;
  material: string;
  materialrec: string;
  ghg: string;
  waterpol: string;
  waterpoltype: string;
  landpol: string;
  landpoltype: string;
  air: string;
  hazmat: string;
  hazwaste: string;
  solidwaste: string;
  solidwasterec: string;
  solidwastedes: string;
  waterwaste: string;
  waterwasterec: string;
  waterwastedes: string;
  productrec: string;
  ecolabel: string;
}

export interface EnviroFormType {
  id: string;
  energy: string;
  renewenergy: string;
  water: string;
  waterrec: string;
  material: string;
  materialrec: string;
  land: string;
  bio: string;
  sensitive: string;
  ghg: string;
  waterpol: string;
  waterpoltype: string;
  landpol: string;
  landpoltype: string;
  air: string;
  hazmat: string;
  hazwaste: string;
  solidwaste: string;
  solidwasterec: string;
  solidwastedes: string;
  waterwaste: string;
  waterwasterec: string;
  waterwastedes: string;
  productrec: string;
  ecolabel: string;
  products: string;
  envirostand: string;
  clean: string;
  envirosus: string;
  suppliers: string;
}

export interface SocialFormType {
  id: string;
  trainh: string;
  trainemp: string;
  emp: string;
  resemp: string;
  hiredemp: string;
  fullemp: string;
  workh: string;
  overtimeh: string;
  empwage: string;
  minwage: string;
  insurance: string;
  femwage: string;
  malwage: string;
  fem: string;
  male: string;
  femboard: string;
  empboard: string;
  disabled: string;
  minority: string;
  older: string;
  socialstand: string;
  ilo: string;
  fire: string;
  medical: string;
  sanitation: string;
  gear: string;
  workacc: string;
  union: string;
  empunion: string;
  bargain: string;
  discri: string;
  child: string;
  forced: string;
  indig: string;
  localemp: string;
  localsup: string;
  donation: string;
  earning: string;
  corrup: string;
  anticomp: string;
  socialsus: string;
  suppliers: Supplier;
  productassess: string;
  product: Product;
  productincident: string;
  privacy: string;
  leaks: string;
  cuscomp: string;
}
